version: '3.9'

services:
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    environment:
      # - NODE_ENV=development
      - PORT=3001
      - DB_HOST=mongo
      - DB_USER=root
      - DB_PASSWORD=pwd
    depends_on:
      - mongo

  app:
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./api/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd